# Generated by Django 4.0.1 on 2022-01-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_rename_correct_anwer_sentence_correct_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='sentence',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='text',
        ),
    ]
