# Generated by Django 4.0.1 on 2022-02-09 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_rename_sentence_sentence_text_rename_word_word_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='word_position',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='sentence',
        ),
        migrations.RemoveField(
            model_name='word',
            name='sentence',
        ),
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_position', models.PositiveIntegerField()),
                ('correct_answer', models.CharField(max_length=256)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blanks', to='questions.sentence')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='blank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='questions.blank'),
        ),
        migrations.AddField(
            model_name='word',
            name='blank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='questions.blank'),
        ),
    ]
